version: '3.8'

networks:
  photosmap-network:
    driver: bridge

services:
  db:
    image: mysql:8.0.33
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    networks:
      - photosmap-network
    volumes:
      - ./photosmap/volume/db/etc/mysql/conf.d:/etc/mysql/conf.d
      - ./photosmap/volume/db/var/lib/mysql:/var/lib/mysql
      - ./photosmap/volume/db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=photos_map
      - MYSQL_ROOT_PASSWORD=root1234
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=1234

  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PROFILES: dev
    image: photosmap:latest
    container_name: photosmap
    restart: always
    ports:
      - '8080:8080'
    networks:
      - photosmap-network
    volumes:
      - ./photosmap/volume/app:/app
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    networks:
      - photosmap-network
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./photosmap/volume/redis/data:/data
      - ./photosmap/volume/redis/usr/local/etc/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./photosmap/volume/redis/etc/redis/users.acl:/etc/redis/users.acl

